### ISSUE TITLE
[Android] core crashed after load content

### ISSUE THREAD

**Issue by duskgao** [libretro/virtualjaguar-libretro#14]
both nightly build & PlayStore build would crashed with the virtualjaguar core last half a month

**Comment by fr500** [comment]
confirmed, happens on PC too and sadly the first broken commit is this one:
https://github.com/libretro/virtualjaguar-libretro/commit/2ee290fcfb6a1e9f52d89efac4f46d4d020810da

**Comment by twinaphex** [comment]
it still works fine on Linux, including that game.

**Comment by fr500** [comment]
It doesn't on Android and on windows...

**Comment by twinaphex** [comment]
Guess we could start debugging it on Windows.

**Comment by Marc34** [comment]
Crashes on Linux too. Nothing works.

**Comment by Shoegzer** [comment]
@Marc34: confirmed, also crashes using Linux Mint 17.2 x64, kernel 3.16.  

I couldn't complete a git bisect, i got to this commit and couldn't even compile to test: f4071059bd2777e33f5b385530b5e0145e598413

I couldn't compile the commit posted above either (2ee290fcfb6a1e9f52d89efac4f46d4d020810da), but I can confirm that the commit immediately prior to that (ffec5c7) compiles fine and the core doesn't crash. 

Hope it helps.

**Comment by r-type** [comment]
the convert (reference/ to pointer) done by this commit 
682b6fde3c2d2f9b4b4c56d693d9d84cefe104a1
forgot few point. 

here is what i used to get core working again on my linux
  
http://pastebin.com/3LfVnVUP

**Comment by twinaphex** [comment]
Thanks for correcting my mistakes, I did a bad rush job at converting that code to C. I think I forgot to respect pointers to pointers here and there.

I pushed a commit of your diff patch and gave you credit, thanks.

Would you perhaps also be willing to look at 4DO? I think I might have made some mistake there too when converting the code from C++ to C. Would be grateful if you could go through it.

**Comment by r-type** [comment]
i m not C expert too , so maybe other mistake possible.
i will look at 4DO.
