### ISSUE TITLE
[Crash] [Windows x64] Rayman crash RA

### ISSUE THREAD

**Issue by stevenstrike** [libretro/virtualjaguar-libretro#19]
Link on libretro.com (+ solution which is reverting to a way older version of the core) : http://libretro.com/forums/showthread.php?t=5629

Nothing useful coming from debug.

**Comment by hizzlekizzle** [comment]
I did some digging through old revisions to find out which commits broke this. There appear to be 2 actual issues:
1.) The first static code analysis commit (https://github.com/libretro/virtualjaguar-libretro/commit/fd9a23f6fc6c5e643ea0f05e000aa65efff5dd40)causes instant segfaults with Rayman (haven't tried other games). This is the last good commit: https://github.com/libretro/virtualjaguar-libretro/commit/5a24d006c149d1e0066ed378f3882eb72229d6fc

2.) The conversion of blitter.cpp to C breaks Rayman right after the initial company logo (first bad commit: https://github.com/libretro/virtualjaguar-libretro/commit/2ee290fcfb6a1e9f52d89efac4f46d4d020810da last good commit: https://github.com/libretro/virtualjaguar-libretro/commit/ffec5c78d41343e28bfd544416a80fbf8988ce47)

So, reverting the blitter.c/pp changes and moving it back to SOURCES_CXX in Makefile.common will get it working up to the static code analysis changes, after which it goes back to immediately segfaulting (i.e., something else is breaking it after that point).

**Comment by r-type** [comment]
should be fixed now
