### ISSUE TITLE
[Windows x64] Unable to load .ROM files from http://reboot.atari.org/

### ISSUE THREAD

**Issue by simonsunnyboy** [libretro/virtualjaguar-libretro#21]
Core v2.1.0 fails to load any .rom marked files found at http://reboot.atari.org/

The Reboot guys tell me, a starndard Virtual Jaguar handles these ok so it should be a problem with Retroarch.

**Comment by r-type** [comment]
i tested Full Circle: Rocketeer from here (the rom) and it works for me

**Comment by JoeMatt** [comment]
Can't confirm. 

Probably fixed in previous tickets.

If anyone still has this issue, Re-open please.
