### ISSUE TITLE
Fork this with Virtual Jaguar RX.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [libretro/virtualjaguar-libretro#49]
Additional Code needs to be incorporated with Virtual Jaguar RX.
There are sigificant improvements in Virtual Jaguar RX, but it is very Linux unfriendly.

**Comment by Zombie-Ryushu** [comment]
https://github.com/djipi/Virtual-Jaguar-Rx

**Comment by twinaphex** [comment]
Good idea, I will be looking into this.

**Comment by djipi** [comment]
Please note, Virtual Jaguar Rx got modification to improve debugging, otherwise few modifications were made to handle performances. The develop branch contains modifications to handle Linux, it should work now.

**Comment by Tasosgemah** [comment]
Any news on this? Can this be ported to libretro? Are there any improvements in accuracy/compatibility compared to the regular Virtual Jaguar?

**Comment by djipi** [comment]
Virtual Jaguar Rx doesn't have improvements in accuracy/compatibility compared to the regular Virtual Jaguar.
The Rx version is focus to integrate a debugger, such feature can be useful to improve the emulator but this is another story.
Merging the Rx version to the Libreto won't be useful.

**Comment by Tasosgemah** [comment]
Ok thanks for the clarification.

**Comment by JoeMatt** [comment]
Reviewed the entire commit history of VJ RX. Agreed, nothing useful for libretro except for debugging perhaps but as a tool, not merged in. Closing.
