### ISSUE TITLE
does it support these games?

### ISSUE THREAD

**Issue by AngelofMe** [libretro/virtualjaguar-libretro#75]
Barkley Shut Up And Jam (Prototype) (1995) 	90% (2.8.17) 	Timing: Ingame is too fast, it shouldn't be like this

Battle Sphere Gold (World) 	95% (2.8.14) 	Graphics: Broken fonts?
Other: Only works with BIOS.

Size: 4194304, MD5: 06f3a61fb712c581aee3599f3a61fa61,
SH1: 49716a6a3a4c6abeea36040f26c4e8cf2a545df7

Brett_Hull_Hockey_(1995) 	80% (2.8.14) 	Graphics: Screen flickers in in-game

Size: 4194304, MD5: 0318d553d1d2e694bb188246bfe49032,
SH1: 77a9277a9b064c2f83c14c101368967ca50a50e4

Fight For Your Life (1996) 	90% (2.8.17) 	Graphics: Blitter Overdrive

Size: 4194304, MD5: 2947e4e2009425a6ac8b26f14a8eea92,
SH1: 9f5b8844d58bb1c174da4824eabbfd8616ba28d2

Fight For Your Life (1996) [a1] 	90% (2.8.17) 	Graphics: Blitter Overdrive

Size: 4194304, MD5: bde3014aaebe4e7a0783a6c5fc921c14,
SH1: 686176f5a7bdaef690d853523a338beb8a93d244

Hover Strike (1995) 	10% (2.8.17) 	Stuck: Hangs in ingame, looks like a problem with GPU emulation - flies out of its program

Size: 2097152, MD5: 51d65ce8171daf0a255a30b44dac07cf,
SH1: 94e615e7a57f7c08645322870121bb32310298f5

Iron Soldier (1994) 	10% (2.8.17) 	Freeze: In-game - seems to be a thread race issue due to lack of memory

arbiter
emulation

Iron Soldier 2 (1997) 	10% (2.8.17) 	Freeze: Before ingame, the problem is identical to the first part

Size: 2097152, MD5: 35ef8cedbfab697e380170e438858d4c,
SH1: 47b9580eb9eea121cf080cdbdc4afe7fb7a19ab5

Phase Zero (2000) (PD) [a1] 	70% (2.8.14) 	Graphics: Screen shaking in in-game and green background on sprites

Size: 2097152, MD5: 4b367a6a538a7451de11de7053c46dff,
SH1: 57882eef55ea903c5eb8a2fcccdd3313474d7a59

Towers II (1996) 	80% (2.8.14) 	Graphics: Screen shaking in ingame

Size: 2097152, MD5: fd8551c8791cbee9b31bd3218670a718,
SH1: f8c14fab50ab04a025d15c3410a6698f6e4c61d3

Val D'Isere Skiing & Snowboarding (1994) 	50% (2.8.12) 	Graphics: Captured full white screen

Size: 2097152, MD5: 1f1145e1042b8cc062c417798392d251,
SH1: 02253d93eef375c8334f1f77a2d8b72fff7a94c6

White Men Can't Jump (1995) 	80% (2.8.12) 	Graphics: Sprites jitter

Size: 4194304, MD5: 22dd3645e3ea99f303694eb5f157ce06,
SH1: 4d16596ac2d991435599e1fe03292adfb25c346d

**Comment by JoeMatt** [comment]
https://docs.libretro.com/library/compatibility/jaguar/
